apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bsky-play-data-pvc
  namespace: bsky-play
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
